In [1]:
import numpy as np

In [7]:
a = np.arange(15)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [16]:
b = np.arange(15).reshape(3, 5)
print(b)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [13]:
print(a.size, a.shape, a.ndim, a.dtype)

15 (15,) 1 int32


In [18]:
c = np.arange(30).reshape(2, 3, 5)
print(c, c.shape, c.ndim)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]] (2, 3, 5) 3
